# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b13b8f8691e8b4d0e9ee2cb12e24d0f79990254fe159105f76fe4fac3419aaebddc9c2187696ae59e91e04081f3e5b69e4421d51ade09ffa6ee07de697e3be1

test:
  secret_key_base: aaa3085ef8d9bf7a6ae9fe1077dec121f7fff508b16c84c621fc601fecd582cc1c2ed8bb071bdf9c8a1fa38351b8b35f45c18b7bc43a1d3366c6ca65a08d41a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
